"""empty message

Revision ID: 0d141e3740ba
Revises: 9d72e9d17467
Create Date: 2020-10-29 10:40:51.779833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d141e3740ba'
down_revision = '9d72e9d17467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventario_tienda', sa.Column('direccion', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventario_tienda', 'direccion')
    # ### end Alembic commands ###
